package Cajas;

import Citas.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class Cajas extends javax.swing.JFrame {
    private DefaultComboBoxModel <Citas> model = new DefaultComboBoxModel <Citas>();
    // We go to the comboBoxModel, in code and parameter we change String for Persona
    private DefaultTableModel tableModel = new DefaultTableModel();
    String nombre,precio,cantidades,ordenCompra,totalAbsoluto = "0";
    private int cantidad;
    private String cantidadFinal;
    private static String nom;
    
    
    public Cajas(String nombre) {
        initComponents();
        this.nom = nombre;
        setLocationRelativeTo(null); // This is to put the window in center
        fillModel(); // This is the method we created
        addTableModel(); // This is the method we created for the table
    }
    

    // To put changes, go to window, in the comboboxmodel, in model, we put custom code and we add model or the name of 
    // the reference we use for the object DefaultComboBoxModel
    private void fillModel() {
        // Here we put the data in a manual way, find other method with arrays, loops or other things
        model.addElement(new Citas("NOMBRE MASCOTA","NOMBRE PROPIETARIO","2500","2500"));
        model.addElement(new Citas("Ceviche Pulpo",cantidadFinal,"3500","2500"));
        model.addElement(new Citas("Ceviche Mixto",cantidadFinal,"6000","2500"));
        model.addElement(new Citas("Ensalada Cesar",cantidadFinal,"1500","2500"));
        model.addElement(new Citas("Ensalada Lechuga",cantidadFinal,"1500","2500"));
        model.addElement(new Citas("Corte New York Steak",cantidadFinal,"18000","2500"));
        model.addElement(new Citas("Corte Tomahawk",cantidadFinal,"20000","2500"));
        model.addElement(new Citas("Corte Cow Boy",cantidadFinal,"20000","2500"));
        model.addElement(new Citas("Corte Entraña",cantidadFinal,"20000","2500"));
        model.addElement(new Citas("Cerveza",cantidadFinal,"1500","2500"));
        model.addElement(new Citas("Tragos",cantidadFinal,"3000","2500"));
        model.addElement(new Citas("Gaseosas",cantidadFinal,"1000","2500"));
        model.addElement(new Citas("Naturales",cantidadFinal,"1500","2500"));
        model.addElement(new Citas("Helado",cantidadFinal,"1500","2500"));
        model.addElement(new Citas("Cheescake",cantidadFinal,"2500","2500"));
    }
    
    // To put changes, go to window, in the table, in model, we put custom code and we add tableModel or the name of 
    // the reference we use for the object DefaultTableModel, to put all data into the table we have to go on table, go
    // to code and in Post-init-code we add the code we want
    private void addTableModel() {
        tableModel.addColumn("Nombre Mascota");
        tableModel.addColumn("Nombre Propietario");
        tableModel.addColumn("Fecha");
        tableModel.addColumn("Hora");
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        buttonMenu = new javax.swing.JButton();
        buttonCajas = new javax.swing.JButton();
        buttonCitas = new javax.swing.JButton();
        buttonCerrarSesion = new javax.swing.JButton();
        logoSalir = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        addButton1 = new javax.swing.JButton();
        totalPagar = new javax.swing.JTextField();
        labelPago = new javax.swing.JLabel();
        panelMenu1 = new javax.swing.JPanel();
        buttonMenu1 = new javax.swing.JButton();
        buttonCajas1 = new javax.swing.JButton();
        buttonCitas1 = new javax.swing.JButton();
        buttonCerrarSesion1 = new javax.swing.JButton();
        logoSalir1 = new javax.swing.JLabel();
        titleOrder1 = new javax.swing.JLabel();
        mailLabel1 = new javax.swing.JLabel();
        expiracionField1 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        panelMenu.setBackground(new java.awt.Color(0, 102, 153));

        buttonMenu.setBackground(new java.awt.Color(36, 47, 65));
        buttonMenu.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        buttonMenu.setForeground(new java.awt.Color(255, 255, 255));
        buttonMenu.setText("Principal");
        buttonMenu.setBorderPainted(false);
        buttonMenu.setContentAreaFilled(false);
        buttonMenu.setDefaultCapable(false);
        buttonMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMenuMouseClicked(evt);
            }
        });
        buttonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMenuActionPerformed(evt);
            }
        });

        buttonCajas.setBackground(new java.awt.Color(36, 47, 65));
        buttonCajas.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        buttonCajas.setForeground(new java.awt.Color(255, 255, 255));
        buttonCajas.setText("Cajas");
        buttonCajas.setBorderPainted(false);
        buttonCajas.setContentAreaFilled(false);
        buttonCajas.setDefaultCapable(false);
        buttonCajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCajasActionPerformed(evt);
            }
        });

        buttonCitas.setBackground(new java.awt.Color(36, 47, 65));
        buttonCitas.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        buttonCitas.setForeground(new java.awt.Color(255, 255, 255));
        buttonCitas.setText("Citas");
        buttonCitas.setBorderPainted(false);
        buttonCitas.setContentAreaFilled(false);
        buttonCitas.setDefaultCapable(false);
        buttonCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCitasActionPerformed(evt);
            }
        });

        buttonCerrarSesion.setBackground(new java.awt.Color(36, 47, 65));
        buttonCerrarSesion.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        buttonCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        buttonCerrarSesion.setText("Cerrar Sesión");
        buttonCerrarSesion.setBorderPainted(false);
        buttonCerrarSesion.setContentAreaFilled(false);
        buttonCerrarSesion.setDefaultCapable(false);
        buttonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCerrarSesionActionPerformed(evt);
            }
        });

        logoSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/user (2).png"))); // NOI18N

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(buttonMenu)
                .addGap(89, 89, 89)
                .addComponent(buttonCajas)
                .addGap(120, 120, 120)
                .addComponent(buttonCitas)
                .addGap(108, 108, 108)
                .addComponent(logoSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCerrarSesion)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonCerrarSesion)
                    .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonMenu)
                        .addComponent(buttonCajas)
                        .addComponent(buttonCitas)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panel.setBackground(new java.awt.Color(255, 255, 255));

        addButton1.setBackground(new java.awt.Color(0, 102, 153));
        addButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        addButton1.setForeground(new java.awt.Color(255, 255, 255));
        addButton1.setText("Consultar");
        addButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton1ActionPerformed(evt);
            }
        });

        totalPagar.setBackground(new java.awt.Color(255, 255, 255));
        totalPagar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalPagar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        labelPago.setBackground(new java.awt.Color(255, 255, 255));
        labelPago.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelPago.setForeground(new java.awt.Color(36, 47, 65));
        labelPago.setText("Total de ingresos del día");

        panelMenu1.setBackground(new java.awt.Color(0, 102, 153));

        buttonMenu1.setBackground(new java.awt.Color(36, 47, 65));
        buttonMenu1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        buttonMenu1.setForeground(new java.awt.Color(255, 255, 255));
        buttonMenu1.setText("Principal");
        buttonMenu1.setBorderPainted(false);
        buttonMenu1.setContentAreaFilled(false);
        buttonMenu1.setDefaultCapable(false);
        buttonMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMenu1MouseClicked(evt);
            }
        });
        buttonMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMenu1ActionPerformed(evt);
            }
        });

        buttonCajas1.setBackground(new java.awt.Color(36, 47, 65));
        buttonCajas1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        buttonCajas1.setForeground(new java.awt.Color(255, 255, 255));
        buttonCajas1.setText("Cajas");
        buttonCajas1.setBorderPainted(false);
        buttonCajas1.setContentAreaFilled(false);
        buttonCajas1.setDefaultCapable(false);
        buttonCajas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCajas1ActionPerformed(evt);
            }
        });

        buttonCitas1.setBackground(new java.awt.Color(36, 47, 65));
        buttonCitas1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        buttonCitas1.setForeground(new java.awt.Color(255, 255, 255));
        buttonCitas1.setText("Citas");
        buttonCitas1.setBorderPainted(false);
        buttonCitas1.setContentAreaFilled(false);
        buttonCitas1.setDefaultCapable(false);
        buttonCitas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCitas1ActionPerformed(evt);
            }
        });

        buttonCerrarSesion1.setBackground(new java.awt.Color(36, 47, 65));
        buttonCerrarSesion1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        buttonCerrarSesion1.setForeground(new java.awt.Color(255, 255, 255));
        buttonCerrarSesion1.setText("Cerrar Sesión");
        buttonCerrarSesion1.setBorderPainted(false);
        buttonCerrarSesion1.setContentAreaFilled(false);
        buttonCerrarSesion1.setDefaultCapable(false);
        buttonCerrarSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCerrarSesion1ActionPerformed(evt);
            }
        });

        logoSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/user (2).png"))); // NOI18N

        javax.swing.GroupLayout panelMenu1Layout = new javax.swing.GroupLayout(panelMenu1);
        panelMenu1.setLayout(panelMenu1Layout);
        panelMenu1Layout.setHorizontalGroup(
            panelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(buttonMenu1)
                .addGap(79, 79, 79)
                .addComponent(buttonCajas1)
                .addGap(61, 61, 61)
                .addComponent(buttonCitas1)
                .addGap(51, 51, 51)
                .addComponent(logoSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCerrarSesion1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenu1Layout.setVerticalGroup(
            panelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMenu1)
                    .addComponent(buttonCajas1)
                    .addComponent(buttonCitas1))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenu1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenu1Layout.createSequentialGroup()
                        .addComponent(logoSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenu1Layout.createSequentialGroup()
                        .addComponent(buttonCerrarSesion1)
                        .addGap(30, 30, 30))))
        );

        titleOrder1.setBackground(new java.awt.Color(36, 47, 65));
        titleOrder1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        titleOrder1.setForeground(new java.awt.Color(36, 47, 65));
        titleOrder1.setText("Ingresos del Día");

        mailLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        mailLabel1.setForeground(new java.awt.Color(36, 47, 65));
        mailLabel1.setText("Ingrese la fecha a consultar");

        expiracionField1.setBackground(new java.awt.Color(255, 255, 255));
        expiracionField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        expiracionField1.setForeground(new java.awt.Color(102, 102, 102));
        try {
            expiracionField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        expiracionField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        expiracionField1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(labelPago)
                        .addGap(18, 18, 18)
                        .addComponent(totalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(titleOrder1)
                                .addGroup(panelLayout.createSequentialGroup()
                                    .addComponent(mailLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(expiracionField1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(panelMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(titleOrder1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mailLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expiracionField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPago, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton1ActionPerformed
        PagoCitas pago = new PagoCitas();
        pago.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addButton1ActionPerformed

    private void buttonMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMenuMouseClicked

    }//GEN-LAST:event_buttonMenuMouseClicked

    private void buttonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMenuActionPerformed

    }//GEN-LAST:event_buttonMenuActionPerformed

    private void buttonCajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCajasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCajasActionPerformed

    private void buttonCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCitasActionPerformed

    }//GEN-LAST:event_buttonCitasActionPerformed

    private void buttonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCerrarSesionActionPerformed

    }//GEN-LAST:event_buttonCerrarSesionActionPerformed

    private void buttonMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMenu1MouseClicked

    }//GEN-LAST:event_buttonMenu1MouseClicked

    private void buttonMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMenu1ActionPerformed

    }//GEN-LAST:event_buttonMenu1ActionPerformed

    private void buttonCajas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCajas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCajas1ActionPerformed

    private void buttonCitas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCitas1ActionPerformed

    }//GEN-LAST:event_buttonCitas1ActionPerformed

    private void buttonCerrarSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCerrarSesion1ActionPerformed

    }//GEN-LAST:event_buttonCerrarSesion1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cajas(nom).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton1;
    private javax.swing.JButton buttonCajas;
    private javax.swing.JButton buttonCajas1;
    private javax.swing.JButton buttonCerrarSesion;
    private javax.swing.JButton buttonCerrarSesion1;
    private javax.swing.JButton buttonCitas;
    private javax.swing.JButton buttonCitas1;
    private javax.swing.JButton buttonMenu;
    private javax.swing.JButton buttonMenu1;
    private javax.swing.JFormattedTextField expiracionField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelPago;
    private javax.swing.JLabel logoSalir;
    private javax.swing.JLabel logoSalir1;
    private javax.swing.JLabel mailLabel1;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelMenu1;
    private javax.swing.JLabel titleOrder1;
    private javax.swing.JTextField totalPagar;
    // End of variables declaration//GEN-END:variables
}
